# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1e6c5c92820e1d84f0e09fda5c8a3bd727690aeac456d420e720bc89ca88b3caa7931f248f44c6c9f931b0abcbceebce031fcf99b8af677a1ee65d341b41dce

test:
  secret_key_base: 42ae27bd6218c70b97d6f01f751e1b5b0d76321cb7567dde29bb67b500db4840eb070acdabb3e574a989e5deed419a55cebea0155b1469079a2d5faa580fbc76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
